version: "3"
services:
  redis: 
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:9.6.3-alpine"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  web:
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes: 
      - /var/app/current/app
    depends_on:
      - postgres
      - redis
