version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - webnet
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thesis
    expose:
      - 5432
    image: "postgres:9.6.3"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - webnet
  web:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: development
    networks:
      - webnet
    ports:
     - "3000:3000"
    volumes:
     - .:/opt/app
    command: yarn run dockerInit
networks:
  webnet: